### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by kozross** [rofl0r/concol#1]
I'm a bit confused about the licensing conditions for this library. Some files say LGPL 2.1+ with linking exception, but it'd be nice to have that clearly stated.

**Comment by rofl0r** [comment]
thanks for reminding me. i added vanilla LGPL 2.1 text file since i couldnt find one that says explicitly "or later" plus mentions the static linking exception in lawyer-speech.
so if you know what would need to be changed to make this explicit, your help is welcome!

**Comment by kozross** [comment]
I think the approach taken by other projects is to use the LGPL2.1 text in a LICENSE file, but then in the COPYING file, make a note that you also give an exception for statlinking. The 'or later' only goes in the source files usually - if you look at the standard GPL/LGPL 'top of file' headers, this is the default.

If you wanna be crystal clear, you might wanna add something like this to the README:

concol is licensed under the GNU Lesser GPL, version 2.1 or later (SPDX code ``LGPL-2.1+``). Additionally, an exception is made for static linking. For details, see the COPYING file.

**Comment by rofl0r** [comment]
what else would COPYING contain in your scenario? is it a copy of LICENSE ?
